# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x13tech.huddle.streams\"\x91\x02\n\x0bTransaction\x12\x11\n\tBETDATAID\x18\x01 \x01(\x05\x12\x11\n\tTIMESTAMP\x18\x02 \x01(\x05\x12\x12\n\nCUSTOMERID\x18\x03 \x01(\x05\x12\x11\n\tOUTCOMEID\x18\x04 \x01(\x05\x12\x15\n\rTRANSACTIONID\x18\x05 \x01(\x05\x12\r\n\x05PRICE\x18\x06 \x01(\x02\x12\x11\n\tUNITSTAKE\x18\x07 \x01(\x02\x12\x0f\n\x07\x45VENTID\x18\x08 \x01(\x05\x12\x18\n\x10\x45VENTDESCRIPTION\x18\t \x01(\t\x12\x19\n\x11MARKETDESCRIPTION\x18\n \x01(\t\x12\x1a\n\x12OUTCOMEDESCRIPTION\x18\x0b \x01(\t\x12\x1a\n\x12SUBTYPEDESCRIPTION\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TRANSACTION']._serialized_start=43
  _globals['_TRANSACTION']._serialized_end=316
# @@protoc_insertion_point(module_scope)
